#!/bin/bash

# Get the battery level
battLevel=$(cat /sys/class/power_supply/BAT0/capacity)

# Get the charging status
chargingStatus=$(cat /sys/class/power_supply/BAT0/status)

# Check and echo "plug" if charging
if [ "$chargingStatus" == "Charging" ]; then
    echo ""

# Check the battery level and echo the corresponding value
if (( battLevel > 75 )); then
    echo ""
elif (( battLevel > 50 )); then
    echo ""
elif (( battLevel > 25 )); then
    echo ""
elif (( battLevel > 5 )); then
    echo ""
else
    echo ""
fi
fi
